from pydantic import BaseModel, Field


class TokenRequest(BaseModel):
    """Request to exchange authorization code for tokens."""

    code: str = Field(
        min_length=1,
        description="Authorization code from Keycloak callback",
    )
    code_verifier: str = Field(
        min_length=43,
        max_length=128,
        description="PKCE code verifier generated by client",
    )
    redirect_uri: str = Field(
        min_length=1,
        description="Redirect URI used in authorization request",
    )


class RefreshRequest(BaseModel):
    """Request to refresh access token."""

    refresh_token: str = Field(
        min_length=1,
        description="Refresh token from previous token response",
    )


class TokenResponse(BaseModel):
    """Token response returned to client."""

    access_token: str = Field(description="JWT access token")
    refresh_token: str = Field(description="Refresh token for renewal")
    token_type: str = Field(default="Bearer", description="Token type")
    expires_in: int = Field(description="Access token lifetime in seconds")


class LogoutRequest(BaseModel):
    """Request to logout and revoke tokens."""

    refresh_token: str = Field(
        min_length=1,
        description="Refresh token to revoke",
    )


class AuthUrlResponse(BaseModel):
    """Authorization URL for OAuth flow."""

    authorization_url: str = Field(
        description="URL to redirect user for login",
    )


class MessageResponse(BaseModel):
    """Simple message response."""

    message: str = Field(description="Response message")