from pydantic import BaseModel, Field


class TokenRequest(BaseModel):
    """Request to exchange authorization code for tokens."""

    code: str = Field(
        min_length=1,
        description="Authorization code from Keycloak callback",
    )
    code_verifier: str = Field(
        min_length=43,
        max_length=128,
        description="PKCE code verifier generated by client",
    )
    redirect_uri: str = Field(
        min_length=1,
        description="Redirect URI used in authorization request",
    )


class AccessTokenResponse(BaseModel):
    """HTTP response body for token endpoints.

    Intentionally excludes refresh_token — it is sent via HttpOnly cookie,
    not in the JSON body. TokenResponse (core) retains refresh_token for
    internal use (OAuthProvider → router).
    """

    access_token: str = Field(description="JWT access token")
    token_type: str = Field(default="Bearer", description="Token type")
    expires_in: int = Field(description="Access token lifetime in seconds")


class AuthUrlResponse(BaseModel):
    """Authorization URL for OAuth flow."""

    authorization_url: str = Field(
        description="URL to redirect user for login",
    )


class MessageResponse(BaseModel):
    """Simple message response."""

    message: str = Field(description="Response message")


class UserResponse(BaseModel):
    """Authenticated user information."""

    id: str = Field(description="Unique user ID")
    username: str = Field(description="Username")
    email: str | None = Field(default=None, description="Email address")
    email_verified: bool = Field(default=False, description="Email verified flag")
    first_name: str | None = Field(default=None, description="First name")
    last_name: str | None = Field(default=None, description="Last name")
    full_name: str | None = Field(default=None, description="Full name")
    roles: list[str] = Field(default_factory=list, description="User roles")
