from pydantic import BaseModel, Field

from fastapi_starter.core.auth.schemas import (
    TokenResponse as TokenResponse,  # re-export
)


class TokenRequest(BaseModel):
    """Request to exchange authorization code for tokens."""

    code: str = Field(
        min_length=1,
        description="Authorization code from Keycloak callback",
    )
    code_verifier: str = Field(
        min_length=43,
        max_length=128,
        description="PKCE code verifier generated by client",
    )
    redirect_uri: str = Field(
        min_length=1,
        description="Redirect URI used in authorization request",
    )


class RefreshRequest(BaseModel):
    """Request to refresh access token."""

    refresh_token: str = Field(
        min_length=1,
        description="Refresh token from previous token response",
    )


class LogoutRequest(BaseModel):
    """Request to logout and revoke tokens."""

    refresh_token: str = Field(
        min_length=1,
        description="Refresh token to revoke",
    )


class AuthUrlResponse(BaseModel):
    """Authorization URL for OAuth flow."""

    authorization_url: str = Field(
        description="URL to redirect user for login",
    )


class MessageResponse(BaseModel):
    """Simple message response."""

    message: str = Field(description="Response message")


class UserResponse(BaseModel):
    """Authenticated user information."""

    id: str = Field(description="Unique user ID")
    username: str = Field(description="Username")
    email: str | None = Field(default=None, description="Email address")
    email_verified: bool = Field(default=False, description="Email verified flag")
    first_name: str | None = Field(default=None, description="First name")
    last_name: str | None = Field(default=None, description="Last name")
    full_name: str | None = Field(default=None, description="Full name")
    roles: list[str] = Field(default_factory=list, description="User roles")
